# Generated by Django 5.0.3 on 2024-04-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinecraftServerManager', '0002_main_delete_mymodelname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('main_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MinecraftServerManager.main')),
                ('username', models.CharField(max_length=16)),
            ],
            bases=('MinecraftServerManager.main',),
        ),
    ]
